name: ci

on:
  push:
    branches:    # only for pushes on master
      - main
  pull_request:  # for all PRs regardless of its base branch

jobs:

  build:
    name: Build and Test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Test
        run: make test

#      - name: Build Android
#        run: make build-android

      - name: Build iOS
        if: matrix.platform == 'macos-latest'
        run: make build-ios
